Repository Kibibit/announce-it, pull requests merged in 2019-07, with the labels that each got.

#38 feat: integrated for semantic-release/exec
  package.json
  src/__snapshots__/announce-it-cli-utils.test.ts.snap
  src/__snapshots__/announce-it.test.ts.snap
  src/__snapshots__/read-package-details.test.ts.snap
  src/announce-it-cli-utils.test.ts
  src/announce-it-cli-utils.ts
  src/announce-it-cli.ts
  src/announce-it.test.ts
  src/announce-it.ts
  src/read-package-details.test.ts
  src/read-package-details.ts
Labels: PR: reviewed-approved, enhancement

#39 integrate self with @semantic-release/exec
  package.json
Labels: PR: unreviewed, enhancement

#40 release/new release
  .gitignore
  README.md
  greenkeeper.json
  jest.config.js
  package.json
  src/__snapshots__/announce-it-cli-utils.test.ts.snap
  src/__snapshots__/announce-it.test.ts.snap
  src/__snapshots__/read-package-details.test.ts.snap
  src/announce-it-cli-utils.test.ts
  src/announce-it-cli-utils.ts
  src/announce-it-cli.ts
  src/announce-it.test.ts
  src/announce-it.ts
  src/read-package-details.test.ts
  src/read-package-details.ts
Labels: PR: unreviewed

#41 Release/release with tweet
  README.md
  bin/announce-it-cli.js
  package.json
  src/announce-it-cli.test.ts
  src/announce-it-cli.ts
Labels: PR: unreviewed, enhancement

#43 chore: fix readme typo
  package.json
Labels: PR: reviewed-approved
